### ISSUE TITLE
add hours and minutes to episode naming

### ISSUE THREAD

**Issue by Bart274** [mmmmmtasty/SportScanner#5]
Is it possible to add the hour and minutes of the start of the event to the episode name before you add the hash of the event? That way different games of the same league on the same day will be placed in chronological order

**Comment by mmmmmtasty** [comment]
I thought a long time about this while writing the scanner originally and I don't think there is any good way to do it. The scanner should take no information from external sources - that is a service provided by the metadatat agent. It also has no idea what other events will come along in the future. It is possible to do web queries but not through the Plex framework, only using other python libraries and there is not enough information on disk to indicate what time the game starts (although that could be maybe added to the filename but that's totally manual and defeats the object of this setup)

So even if you DO start doing metadata lookups in the scanner then what happens if the event is not yet in the metadata source? What happens with multiple events starting at the same time? Does the episode number suddenly change after the metadata IS added?

All in all I think that sports just don't fit that well into the TV Show model which is why I have to make a few approximations on the way through and this is one of them.

I just don't feel that there is a proper way to do it! Feel free to try and convince me though before I close this and don't do it :)

MmmmmTasty

**Comment by Bart274** [comment]
I mixed the scanner and the metadata agent together, I thought you used the metadata agent while scanning. Adding those times to the file name could be possible, but I don't think that would be necessary.
I'll close this issue. :)
